name: Auto Commit Bot

on:
  schedule:
    - cron: '0 8 * * *'   # 8 AM UTC
    - cron: '0 14 * * *'  # 2 PM UTC
    - cron: '0 20 * * *'  # 8 PM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - name: Run autocommit script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: python autocommit.py
      - name: Commit changes
        run: |
          git config --global user.name 'Auto Commit Bot'
          git config --global user.email 'bot@users.noreply.github.com'
          git add .
          git commit -m "Auto-commit by GitHub Actions" || echo "No changes to commit"
          git push